# Generated by Django 5.2.12 on 2026-03-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_contact_phone_order_created_at_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('basket', 'Basket'), ('new', 'New'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped')], default='basket', max_length=20),
        ),
    ]
